import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useSetUserLanguagePreference, useGetUserLanguagePreference } from '../hooks/useQueries';
import { useInternetIdentity } from '../hooks/useInternetIdentity';

type Language = 'pl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pl: {
    'login.title': 'Zaloguj się',
    'login.subtitle': 'Użyj Internet Identity, aby kontynuować',
    'login.description': 'Użyj Internet Identity, aby kontynuować',
    'login.button': 'Zaloguj się',
    'login.loggingIn': 'Logowanie...',
    'login.connecting': 'Łączenie...',
    'login.logout': 'Wyloguj',
    'login.privacy': 'Twoja tożsamość jest bezpieczna i prywatna',
    'login.loggedOut': 'Wylogowano pomyślnie',
    'header.title': 'Moja Aplikacja',
    'footer.builtWith': 'Zbudowane z',
    'footer.using': 'używając',
    'app.title': 'Moja Aplikacja',
    'general.loading': 'Ładowanie...',
    'books.new': 'Dodaj książkę',
    'books.myBooks': 'Moje Książki',
    'books.subtitle': 'Zarządzaj swoimi książkami i rozdziałami',
    'books.title': 'Moje Książki',
    'books.create': 'Utwórz Książkę',
    'books.edit': 'Edytuj',
    'books.delete': 'Usuń',
    'books.open': 'Otwórz',
    'books.empty': 'Nie masz jeszcze żadnych książek',
    'books.noBooks': 'Nie masz jeszcze żadnych książek',
    'books.createFirst': 'Utwórz swoją pierwszą książkę, aby rozpocząć pisanie',
    'books.titlePlaceholder': 'Tytuł książki',
    'books.descriptionPlaceholder': 'Opis książki',
    'books.createButton': 'Utwórz',
    'books.cancel': 'Anuluj',
    'books.created': 'Książka utworzona',
    'books.updated': 'Książka zaktualizowana',
    'books.deleted': 'usunięta',
    'books.createFailed': 'Nie udało się utworzyć książki',
    'books.updateFailed': 'Nie udało się zaktualizować książki',
    'books.deleteFailed': 'Nie udało się usunąć książki',
    'books.titleRequired': 'Tytuł jest wymagany',
    'books.creating': 'Tworzenie...',
    'books.updating': 'Aktualizowanie...',
    'books.editTitle': 'Edytuj Książkę',
    'books.unauthorized': 'Brak autoryzacji',
    'books.backendNotReady': 'Backend nie jest jeszcze gotowy. Proszę czekać...',
    'books.connecting': 'Łączenie...',
    'books.connectionError': 'Nie można połączyć się z backendem. Sprawdź połączenie i spróbuj ponownie.',
    'books.retry': 'Ponów',
    'books.retryingConnection': 'Ponowne łączenie...',
    'book.chapters': 'rozdziałów',
    'book.chaptersCount': '{count} rozdziałów',
    'book.backToBooks': 'Powrót do książek',
    'book.createChapter': 'Utwórz Rozdział',
    'book.noChapters': 'Brak rozdziałów',
    'book.createFirstChapter': 'Utwórz swój pierwszy rozdział',
    'book.chapterTitlePlaceholder': 'Tytuł rozdziału',
    'book.chapterCreated': 'Rozdział utworzony',
    'book.chapterCreateFailed': 'Nie udało się utworzyć rozdziału',
    'book.chapterDeleted': 'Rozdział usunięty',
    'book.chapterDeleteFailed': 'Nie udało się usunąć rozdziału',
    'editor.loading': 'Ładowanie...',
    'editor.notFound': 'Rozdział nie znaleziony',
    'editor.titlePlaceholder': 'Tytuł rozdziału',
    'editor.contentPlaceholder': 'Zacznij pisać...',
    'editor.save': 'Zapisz',
    'editor.saving': 'Zapisywanie...',
    'editor.saved': 'Zapisano',
    'editor.saveFailed': 'Nie udało się zapisać',
    'editor.spellCheck': 'Sprawdź pisownię',
    'editor.checking': 'Sprawdzanie...',
    'editor.analyze': 'Analizuj',
    'editor.annotations': 'Notatki',
    'editor.export': 'Eksportuj',
    'editor.exportDocx': 'Export to DOCX',
    'editor.exportPdf': 'Export to PDF',
    'editor.exporting': 'Exporting...',
    'editor.noContent': 'Brak treści do sprawdzenia',
    'editor.noContentAnalyze': 'Brak treści do analizy',
    'editor.noContentExport': 'Brak treści do eksportu',
    'editor.analysisComplete': 'Analiza zakończona',
    'editor.analysisFailed': 'Nie udało się przeanalizować tekstu',
    'editor.spellCheckComplete': 'Sprawdzanie pisowni zakończone',
    'editor.spellCheckFailed': 'Nie udało się sprawdzić pisowni',
    'editor.exportSuccess': 'Eksport zakończony sukcesem',
    'editor.exportFailed': 'Nie udało się wyeksportować',
    'editor.improve': 'Popraw tekst',
    'editor.improving': 'Poprawianie...',
    'editor.improved': 'Tekst poprawiony',
    'editor.improveFailed': 'Nie udało się poprawić tekstu',
    'editor.noSelection': 'Zaznacz tekst do poprawy',
    'editor.wordCount': 'Liczba słów: {count}',
    'annotations.title': 'Notatki',
    'annotations.add': 'Dodaj notatkę',
    'annotations.placeholder': 'Wpisz swoją notatkę...',
    'annotations.save': 'Zapisz',
    'annotations.cancel': 'Anuluj',
    'annotations.edit': 'Edytuj',
    'annotations.delete': 'Usuń',
    'annotations.empty': 'Brak notatek',
    'annotations.added': 'Notatka dodana',
    'annotations.updated': 'Notatka zaktualizowana',
    'annotations.deleted': 'Notatka usunięta',
    'annotations.addFailed': 'Nie udało się dodać notatki',
    'annotations.updateFailed': 'Nie udało się zaktualizować notatki',
    'annotations.deleteFailed': 'Nie udało się usunąć notatki',
    'tts.title': 'Synteza mowy',
    'tts.voice': 'Głos',
    'tts.speed': 'Prędkość',
    'tts.play': 'Odtwórz',
    'tts.pause': 'Pauza',
    'tts.stop': 'Stop',
    'tts.noContent': 'Brak treści do odtworzenia',
    'tts.narrator': 'Narrator',
    'tts.female': 'Kobieta',
    'tts.male': 'Mężczyzna',
    'tts.other': 'Inne',
    'tts.slow': 'Wolno',
    'tts.normal': 'Normalnie',
    'tts.fast': 'Szybko',
    'tts.veryFast': 'Bardzo szybko',
    'analysis.title': 'Analiza tekstu',
    'analysis.close': 'Zamknij',
    'profile.setup': 'Konfiguracja profilu',
    'profile.name': 'Imię',
    'profile.namePlaceholder': 'Wpisz swoje imię',
    'profile.save': 'Zapisz',
    'profile.saving': 'Zapisywanie...',
    'profile.saved': 'Profil zapisany',
    'profile.saveFailed': 'Nie udało się zapisać profilu',
    'profile.nameRequired': 'Imię jest wymagane',
    'voice.search': 'Szukaj głosem',
    'voice.searching': 'Szukanie...',
    'voice.notFound': 'Nie znaleziono',
    'voice.found': 'Znaleziono: {word}',
    'voice.error': 'Błąd rozpoznawania mowy',
    'synonym.search': 'Szukaj synonimu',
    'synonym.searching': 'Szukanie...',
    'synonym.notFound': 'Nie znaleziono synonimów',
    'synonym.found': 'Znaleziono {count} synonimów',
    'synonym.error': 'Błąd wyszukiwania synonimów',
    'synonym.placeholder': 'Wpisz słowo...',
    'synonym.retry': 'Spróbuj ponownie',
    'language.english': 'English',
    'language.polish': 'Polski',
    'theme.toggle': 'Przełącz motyw',
  },
  en: {
    'login.title': 'Sign In',
    'login.subtitle': 'Use Internet Identity to continue',
    'login.description': 'Use Internet Identity to continue',
    'login.button': 'Sign In',
    'login.loggingIn': 'Signing in...',
    'login.connecting': 'Connecting...',
    'login.logout': 'Logout',
    'login.privacy': 'Your identity is secure and private',
    'login.loggedOut': 'Logged out successfully',
    'header.title': 'My Application',
    'footer.builtWith': 'Built with',
    'footer.using': 'using',
    'app.title': 'My Application',
    'general.loading': 'Loading...',
    'books.new': 'Add book',
    'books.myBooks': 'My Books',
    'books.subtitle': 'Manage your books and chapters',
    'books.title': 'My Books',
    'books.create': 'Create Book',
    'books.edit': 'Edit',
    'books.delete': 'Delete',
    'books.open': 'Open',
    'books.empty': 'You don\'t have any books yet',
    'books.noBooks': 'You don\'t have any books yet',
    'books.createFirst': 'Create your first book to start writing',
    'books.titlePlaceholder': 'Book title',
    'books.descriptionPlaceholder': 'Book description',
    'books.createButton': 'Create',
    'books.cancel': 'Cancel',
    'books.created': 'Book created',
    'books.updated': 'Book updated',
    'books.deleted': 'deleted',
    'books.createFailed': 'Failed to create book',
    'books.updateFailed': 'Failed to update book',
    'books.deleteFailed': 'Failed to delete book',
    'books.titleRequired': 'Title is required',
    'books.creating': 'Creating...',
    'books.updating': 'Updating...',
    'books.editTitle': 'Edit Book',
    'books.unauthorized': 'Unauthorized',
    'books.backendNotReady': 'Backend is not ready yet. Please wait...',
    'books.connecting': 'Connecting...',
    'books.connectionError': 'Cannot connect to backend. Check your connection and try again.',
    'books.retry': 'Retry',
    'books.retryingConnection': 'Retrying connection...',
    'book.chapters': 'chapters',
    'book.chaptersCount': '{count} chapters',
    'book.backToBooks': 'Back to books',
    'book.createChapter': 'Create Chapter',
    'book.noChapters': 'No chapters',
    'book.createFirstChapter': 'Create your first chapter',
    'book.chapterTitlePlaceholder': 'Chapter title',
    'book.chapterCreated': 'Chapter created',
    'book.chapterCreateFailed': 'Failed to create chapter',
    'book.chapterDeleted': 'Chapter deleted',
    'book.chapterDeleteFailed': 'Failed to delete chapter',
    'editor.loading': 'Loading...',
    'editor.notFound': 'Chapter not found',
    'editor.titlePlaceholder': 'Chapter title',
    'editor.contentPlaceholder': 'Start writing...',
    'editor.save': 'Save',
    'editor.saving': 'Saving...',
    'editor.saved': 'Saved',
    'editor.saveFailed': 'Failed to save',
    'editor.spellCheck': 'Check spelling',
    'editor.checking': 'Checking...',
    'editor.analyze': 'Analyze',
    'editor.annotations': 'Notes',
    'editor.export': 'Export',
    'editor.exportDocx': 'Export to DOCX',
    'editor.exportPdf': 'Export to PDF',
    'editor.exporting': 'Exporting...',
    'editor.noContent': 'No content to check',
    'editor.noContentAnalyze': 'No content to analyze',
    'editor.noContentExport': 'No content to export',
    'editor.analysisComplete': 'Analysis complete',
    'editor.analysisFailed': 'Failed to analyze text',
    'editor.spellCheckComplete': 'Spell check complete',
    'editor.spellCheckFailed': 'Failed to check spelling',
    'editor.exportSuccess': 'Export successful',
    'editor.exportFailed': 'Failed to export',
    'editor.improve': 'Improve text',
    'editor.improving': 'Improving...',
    'editor.improved': 'Text improved',
    'editor.improveFailed': 'Failed to improve text',
    'editor.noSelection': 'Select text to improve',
    'editor.wordCount': 'Word count: {count}',
    'annotations.title': 'Notes',
    'annotations.add': 'Add note',
    'annotations.placeholder': 'Enter your note...',
    'annotations.save': 'Save',
    'annotations.cancel': 'Cancel',
    'annotations.edit': 'Edit',
    'annotations.delete': 'Delete',
    'annotations.empty': 'No notes',
    'annotations.added': 'Note added',
    'annotations.updated': 'Note updated',
    'annotations.deleted': 'Note deleted',
    'annotations.addFailed': 'Failed to add note',
    'annotations.updateFailed': 'Failed to update note',
    'annotations.deleteFailed': 'Failed to delete note',
    'tts.title': 'Text to Speech',
    'tts.voice': 'Voice',
    'tts.speed': 'Speed',
    'tts.play': 'Play',
    'tts.pause': 'Pause',
    'tts.stop': 'Stop',
    'tts.noContent': 'No content to play',
    'tts.narrator': 'Narrator',
    'tts.female': 'Female',
    'tts.male': 'Male',
    'tts.other': 'Other',
    'tts.slow': 'Slow',
    'tts.normal': 'Normal',
    'tts.fast': 'Fast',
    'tts.veryFast': 'Very Fast',
    'analysis.title': 'Text Analysis',
    'analysis.close': 'Close',
    'profile.setup': 'Profile Setup',
    'profile.name': 'Name',
    'profile.namePlaceholder': 'Enter your name',
    'profile.save': 'Save',
    'profile.saving': 'Saving...',
    'profile.saved': 'Profile saved',
    'profile.saveFailed': 'Failed to save profile',
    'profile.nameRequired': 'Name is required',
    'voice.search': 'Voice search',
    'voice.searching': 'Searching...',
    'voice.notFound': 'Not found',
    'voice.found': 'Found: {word}',
    'voice.error': 'Speech recognition error',
    'synonym.search': 'Search synonym',
    'synonym.searching': 'Searching...',
    'synonym.notFound': 'No synonyms found',
    'synonym.found': 'Found {count} synonyms',
    'synonym.error': 'Synonym search error',
    'synonym.placeholder': 'Enter word...',
    'synonym.retry': 'Try again',
    'language.english': 'English',
    'language.polish': 'Polski',
    'theme.toggle': 'Toggle theme',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('pl');
  const { identity } = useInternetIdentity();
  const setUserLanguagePreference = useSetUserLanguagePreference();
  const { data: userLanguagePreference } = useGetUserLanguagePreference();

  useEffect(() => {
    if (userLanguagePreference) {
      setLanguageState(userLanguagePreference as Language);
    }
  }, [userLanguagePreference]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (identity && !identity.getPrincipal().isAnonymous()) {
      setUserLanguagePreference.mutate(lang);
    }
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, paramValue);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
