import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useSetUserLanguagePreference, useGetUserLanguagePreference } from '../hooks/useQueries';
import { useInternetIdentity } from '../hooks/useInternetIdentity';

type Language = 'pl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pl: {
    'login.title': 'Zaloguj się',
    'login.description': 'Użyj Internet Identity, aby kontynuować',
    'login.button': 'Zaloguj się',
    'login.loggingIn': 'Logowanie...',
    'login.logout': 'Wyloguj',
    'header.title': 'Moja Aplikacja',
    'footer.builtWith': 'Zbudowane z',
    'footer.using': 'używając',
    'books.title': 'Moje Książki',
    'books.create': 'Utwórz Książkę',
    'books.edit': 'Edytuj',
    'books.delete': 'Usuń',
    'books.open': 'Otwórz',
    'books.noBooks': 'Nie masz jeszcze żadnych książek',
    'books.createFirst': 'Utwórz swoją pierwszą książkę, aby rozpocząć pisanie',
    'books.titlePlaceholder': 'Tytuł książki',
    'books.descriptionPlaceholder': 'Opis książki',
    'books.createButton': 'Utwórz',
    'books.cancel': 'Anuluj',
    'books.created': 'Książka utworzona',
    'books.updated': 'Książka zaktualizowana',
    'books.deleted': 'Książka usunięta',
    'books.createFailed': 'Nie udało się utworzyć książki',
    'books.updateFailed': 'Nie udało się zaktualizować książki',
    'books.deleteFailed': 'Nie udało się usunąć książki',
    'books.backendNotReady': 'Backend nie jest jeszcze gotowy. Proszę czekać...',
    'book.chapters': 'rozdziałów',
    'book.chaptersCount': '{count} rozdziałów',
    'book.backToBooks': 'Powrót do książek',
    'book.createChapter': 'Utwórz Rozdział',
    'book.noChapters': 'Brak rozdziałów',
    'book.createFirstChapter': 'Utwórz swój pierwszy rozdział',
    'book.chapterTitlePlaceholder': 'Tytuł rozdziału',
    'book.chapterCreated': 'Rozdział utworzony',
    'book.chapterCreateFailed': 'Nie udało się utworzyć rozdziału',
    'book.chapterDeleted': 'Rozdział usunięty',
    'book.chapterDeleteFailed': 'Nie udało się usunąć rozdziału',
    'editor.loading': 'Ładowanie...',
    'editor.notFound': 'Rozdział nie znaleziony',
    'editor.titlePlaceholder': 'Tytuł rozdziału',
    'editor.contentPlaceholder': 'Zacznij pisać...',
    'editor.save': 'Zapisz',
    'editor.saving': 'Zapisywanie...',
    'editor.saved': 'Zapisano',
    'editor.saveFailed': 'Nie udało się zapisać',
    'editor.spellCheck': 'Sprawdź pisownię',
    'editor.checking': 'Sprawdzanie...',
    'editor.analyze': 'Analizuj',
    'editor.annotations': 'Notatki',
    'editor.export': 'Eksportuj',
    'editor.exportDocx': 'Export to DOCX',
    'editor.exportPdf': 'Export to PDF',
    'editor.exporting': 'Exporting...',
    'editor.noContent': 'Brak treści do sprawdzenia',
    'editor.noContentAnalyze': 'Brak treści do analizy',
    'editor.noContentExport': 'Brak treści do eksportu',
    'editor.analysisComplete': 'Analiza zakończona',
    'editor.analysisFailed': 'Nie udało się przeanalizować tekstu',
    'editor.exportSuccess': 'Export successful',
    'editor.exportFailed': 'Export failed',
    'editor.highlight': 'Podświetl',
    'editor.selectColor': 'Wybierz kolor',
    'editor.applyHighlight': 'Zastosuj podświetlenie',
    'editor.removeHighlight': 'Usuń podświetlenie',
    'editor.bold': 'Pogrubienie',
    'editor.removeBold': 'Usuń pogrubienie',
    'editor.improve': 'Popraw',
    'editor.insertImage': 'Wstaw obraz',
    'editor.uploading': 'Przesyłanie',
    'editor.imageInserted': 'Obraz wstawiony',
    'editor.imageUploadFailed': 'Nie udało się przesłać obrazu',
    'editor.invalidImageType': 'Nieprawidłowy typ pliku. Dozwolone: PNG, JPG, JPEG',
    'editor.imageTooLarge': 'Plik jest za duży. Maksymalny rozmiar: 5MB',
    'editor.imageLoadFailed': 'Nie udało się załadować obrazu',
    'highlight.noSelection': 'Zaznacz tekst, aby podświetlić',
    'highlight.added': 'Podświetlenie dodane',
    'highlight.addFailed': 'Nie udało się dodać podświetlenia',
    'highlight.removed': 'Podświetlenie usunięte',
    'highlight.removeFailed': 'Nie udało się usunąć podświetlenia',
    'bold.noSelection': 'Zaznacz tekst, aby pogrubić',
    'bold.added': 'Pogrubienie dodane',
    'bold.addFailed': 'Nie udało się dodać pogrubienia',
    'bold.removed': 'Pogrubienie usunięte',
    'bold.removeFailed': 'Nie udało się usunąć pogrubienia',
    'improve.noSelection': 'Zaznacz tekst, aby poprawić',
    'improve.failed': 'Nie udało się poprawić tekstu',
    'improve.title': 'Popraw tekst',
    'improve.description': 'Porównaj oryginalny tekst z poprawionym',
    'improve.original': 'Oryginalny tekst',
    'improve.improved': 'Poprawiony tekst',
    'improve.accept': 'Zaakceptuj',
    'improve.cancel': 'Anuluj',
    'improve.accepted': 'Tekst poprawiony',
    'annotations.title': 'Notatki',
    'annotations.add': 'Dodaj notatkę',
    'annotations.placeholder': 'Wpisz swoją notatkę...',
    'annotations.save': 'Zapisz',
    'annotations.edit': 'Edytuj',
    'annotations.delete': 'Usuń',
    'annotations.noAnnotations': 'Brak notatek',
    'annotations.added': 'Notatka dodana',
    'annotations.updated': 'Notatka zaktualizowana',
    'annotations.deleted': 'Notatka usunięta',
    'annotations.addFailed': 'Nie udało się dodać notatki',
    'annotations.updateFailed': 'Nie udało się zaktualizować notatki',
    'annotations.deleteFailed': 'Nie udało się usunąć notatki',
    'tts.title': 'Czytanie tekstu',
    'tts.voice': 'Głos',
    'tts.speed': 'Prędkość',
    'tts.play': 'Odtwórz',
    'tts.pause': 'Pauza',
    'tts.stop': 'Stop',
    'tts.slow': 'Wolno',
    'tts.normal': 'Normalnie',
    'tts.fast': 'Szybko',
    'tts.veryFast': 'Bardzo szybko',
    'tts.narrator': 'Narrator',
    'tts.female': 'Kobieta',
    'tts.male': 'Mężczyzna',
    'tts.other': 'Inne',
    'analysis.title': 'Analiza tekstu',
    'analysis.close': 'Zamknij',
    'analysis.analyzing': 'Analizowanie...',
    'voiceSearch.placeholder': 'Wyszukaj głosowo...',
    'voiceSearch.start': 'Rozpocznij nagrywanie',
    'voiceSearch.stop': 'Zatrzymaj nagrywanie',
    'voiceSearch.searching': 'Wyszukiwanie...',
    'voiceSearch.notFound': 'Nie znaleziono',
    'voiceSearch.error': 'Błąd wyszukiwania głosowego',
    'synonym.placeholder': 'Wyszukaj synonimy...',
    'synonym.search': 'Szukaj',
    'synonym.voiceSearch': 'Wyszukaj głosowo',
    'synonym.searching': 'Wyszukiwanie...',
    'synonym.noResults': 'Brak wyników',
    'synonym.error': 'Błąd wyszukiwania synonimów',
    'synonymSearch.found': 'Znaleziono {count} synonimów',
    'profile.setup': 'Konfiguracja profilu',
    'profile.description': 'Podaj swoje imię, aby kontynuować',
    'profile.namePlaceholder': 'Twoje imię',
    'profile.save': 'Zapisz',
    'profile.saving': 'Zapisywanie...',
    'profile.saved': 'Profil zapisany',
    'profile.saveFailed': 'Nie udało się zapisać profilu',
    'profile.nameRequired': 'Imię jest wymagane',
  },
  en: {
    'login.title': 'Log In',
    'login.description': 'Use Internet Identity to continue',
    'login.button': 'Log In',
    'login.loggingIn': 'Logging in...',
    'login.logout': 'Logout',
    'header.title': 'My Application',
    'footer.builtWith': 'Built with',
    'footer.using': 'using',
    'books.title': 'My Books',
    'books.create': 'Create Book',
    'books.edit': 'Edit',
    'books.delete': 'Delete',
    'books.open': 'Open',
    'books.noBooks': 'You don\'t have any books yet',
    'books.createFirst': 'Create your first book to start writing',
    'books.titlePlaceholder': 'Book title',
    'books.descriptionPlaceholder': 'Book description',
    'books.createButton': 'Create',
    'books.cancel': 'Cancel',
    'books.created': 'Book created',
    'books.updated': 'Book updated',
    'books.deleted': 'Book deleted',
    'books.createFailed': 'Failed to create book',
    'books.updateFailed': 'Failed to update book',
    'books.deleteFailed': 'Failed to delete book',
    'books.backendNotReady': 'Backend is not ready yet. Please wait...',
    'book.chapters': 'chapters',
    'book.chaptersCount': '{count} chapters',
    'book.backToBooks': 'Back to books',
    'book.createChapter': 'Create Chapter',
    'book.noChapters': 'No chapters',
    'book.createFirstChapter': 'Create your first chapter',
    'book.chapterTitlePlaceholder': 'Chapter title',
    'book.chapterCreated': 'Chapter created',
    'book.chapterCreateFailed': 'Failed to create chapter',
    'book.chapterDeleted': 'Chapter deleted',
    'book.chapterDeleteFailed': 'Failed to delete chapter',
    'editor.loading': 'Loading...',
    'editor.notFound': 'Chapter not found',
    'editor.titlePlaceholder': 'Chapter title',
    'editor.contentPlaceholder': 'Start writing...',
    'editor.save': 'Save',
    'editor.saving': 'Saving...',
    'editor.saved': 'Saved',
    'editor.saveFailed': 'Failed to save',
    'editor.spellCheck': 'Spell Check',
    'editor.checking': 'Checking...',
    'editor.analyze': 'Analyze',
    'editor.annotations': 'Notes',
    'editor.export': 'Export',
    'editor.exportDocx': 'Export to DOCX',
    'editor.exportPdf': 'Export to PDF',
    'editor.exporting': 'Exporting...',
    'editor.noContent': 'No content to check',
    'editor.noContentAnalyze': 'No content to analyze',
    'editor.noContentExport': 'No content to export',
    'editor.analysisComplete': 'Analysis complete',
    'editor.analysisFailed': 'Failed to analyze text',
    'editor.exportSuccess': 'Export successful',
    'editor.exportFailed': 'Export failed',
    'editor.highlight': 'Highlight',
    'editor.selectColor': 'Select color',
    'editor.applyHighlight': 'Apply highlight',
    'editor.removeHighlight': 'Remove highlight',
    'editor.bold': 'Bold',
    'editor.removeBold': 'Remove bold',
    'editor.improve': 'Improve',
    'editor.insertImage': 'Insert Image',
    'editor.uploading': 'Uploading',
    'editor.imageInserted': 'Image inserted',
    'editor.imageUploadFailed': 'Failed to upload image',
    'editor.invalidImageType': 'Invalid file type. Allowed: PNG, JPG, JPEG',
    'editor.imageTooLarge': 'File is too large. Maximum size: 5MB',
    'editor.imageLoadFailed': 'Failed to load image',
    'highlight.noSelection': 'Select text to highlight',
    'highlight.added': 'Highlight added',
    'highlight.addFailed': 'Failed to add highlight',
    'highlight.removed': 'Highlight removed',
    'highlight.removeFailed': 'Failed to remove highlight',
    'bold.noSelection': 'Select text to bold',
    'bold.added': 'Bold added',
    'bold.addFailed': 'Failed to add bold',
    'bold.removed': 'Bold removed',
    'bold.removeFailed': 'Failed to remove bold',
    'improve.noSelection': 'Select text to improve',
    'improve.failed': 'Failed to improve text',
    'improve.title': 'Improve Text',
    'improve.description': 'Compare original text with improved version',
    'improve.original': 'Original text',
    'improve.improved': 'Improved text',
    'improve.accept': 'Accept',
    'improve.cancel': 'Cancel',
    'improve.accepted': 'Text improved',
    'annotations.title': 'Notes',
    'annotations.add': 'Add note',
    'annotations.placeholder': 'Type your note...',
    'annotations.save': 'Save',
    'annotations.edit': 'Edit',
    'annotations.delete': 'Delete',
    'annotations.noAnnotations': 'No notes',
    'annotations.added': 'Note added',
    'annotations.updated': 'Note updated',
    'annotations.deleted': 'Note deleted',
    'annotations.addFailed': 'Failed to add note',
    'annotations.updateFailed': 'Failed to update note',
    'annotations.deleteFailed': 'Failed to delete note',
    'tts.title': 'Text to Speech',
    'tts.voice': 'Voice',
    'tts.speed': 'Speed',
    'tts.play': 'Play',
    'tts.pause': 'Pause',
    'tts.stop': 'Stop',
    'tts.slow': 'Slow',
    'tts.normal': 'Normal',
    'tts.fast': 'Fast',
    'tts.veryFast': 'Very Fast',
    'tts.narrator': 'Narrator',
    'tts.female': 'Female',
    'tts.male': 'Male',
    'tts.other': 'Other',
    'analysis.title': 'Text Analysis',
    'analysis.close': 'Close',
    'analysis.analyzing': 'Analyzing...',
    'voiceSearch.placeholder': 'Voice search...',
    'voiceSearch.start': 'Start recording',
    'voiceSearch.stop': 'Stop recording',
    'voiceSearch.searching': 'Searching...',
    'voiceSearch.notFound': 'Not found',
    'voiceSearch.error': 'Voice search error',
    'synonym.placeholder': 'Search synonyms...',
    'synonym.search': 'Search',
    'synonym.voiceSearch': 'Voice search',
    'synonym.searching': 'Searching...',
    'synonym.noResults': 'No results',
    'synonym.error': 'Synonym search error',
    'synonymSearch.found': 'Found {count} synonyms',
    'profile.setup': 'Profile Setup',
    'profile.description': 'Enter your name to continue',
    'profile.namePlaceholder': 'Your name',
    'profile.save': 'Save',
    'profile.saving': 'Saving...',
    'profile.saved': 'Profile saved',
    'profile.saveFailed': 'Failed to save profile',
    'profile.nameRequired': 'Name is required',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('pl');
  const setUserLanguagePreference = useSetUserLanguagePreference();
  const { data: userLanguagePreference } = useGetUserLanguagePreference();
  const { identity } = useInternetIdentity();

  useEffect(() => {
    if (userLanguagePreference) {
      setLanguageState(userLanguagePreference as Language);
    }
  }, [userLanguagePreference]);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    if (identity) {
      try {
        await setUserLanguagePreference.mutateAsync(lang);
      } catch (error) {
        console.error('Failed to save language preference:', error);
      }
    }
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, paramValue);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
