/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Annotation {
  'id' : string,
  'content' : string,
  'chapterId' : string,
}
export interface BoldRange {
  'end' : bigint,
  'chapterId' : string,
  'start' : bigint,
}
export interface Book {
  'id' : string,
  'title' : string,
  'description' : string,
}
export interface Chapter {
  'id' : string,
  'title' : string,
  'content' : string,
  'characterCount' : bigint,
  'bookId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Highlight {
  'end' : bigint,
  'color' : string,
  'text' : string,
  'chapterId' : string,
  'start' : bigint,
}
export interface ImageAttachment {
  'id' : string,
  'contentType' : string,
  'data' : ExternalBlob,
  'size' : bigint,
  'filename' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoicePreference {
  'voice' : string,
  'chapterId' : string,
  'speed' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAnnotation' : ActorMethod<[string, string, string], undefined>,
  'addAttachmentToChapter' : ActorMethod<[string, string], undefined>,
  'addBoldRange' : ActorMethod<[string, bigint, bigint], undefined>,
  'addHighlight' : ActorMethod<
    [string, bigint, bigint, string, string],
    undefined
  >,
  'adjustBoldRanges' : ActorMethod<[string, bigint, bigint], undefined>,
  'adjustHighlights' : ActorMethod<[string, bigint, bigint], undefined>,
  'analyzePolishWriting' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkEnglishSpelling' : ActorMethod<[string], string>,
  'checkPolishSpelling' : ActorMethod<[string], string>,
  'clearBoldRanges' : ActorMethod<[string], undefined>,
  'clearHighlights' : ActorMethod<[string], undefined>,
  'createBook' : ActorMethod<[string, string, string], undefined>,
  'createChapter' : ActorMethod<[string, string, string, string], undefined>,
  'deleteAnnotation' : ActorMethod<[string], undefined>,
  'deleteBook' : ActorMethod<[string], undefined>,
  'deleteChapter' : ActorMethod<[string], undefined>,
  'deleteImageAttachment' : ActorMethod<[string], undefined>,
  'exportChapterAsDocx' : ActorMethod<[string], [] | [Uint8Array]>,
  'exportChapterAsPdf' : ActorMethod<[string], [] | [Uint8Array]>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAnnotationsForChapter' : ActorMethod<[string], Array<Annotation>>,
  'getAttachmentsForChapter' : ActorMethod<[string], Array<string>>,
  'getAvailableFonts' : ActorMethod<[], Array<string>>,
  'getBoldRanges' : ActorMethod<[string], Array<BoldRange>>,
  'getBook' : ActorMethod<[string], [] | [Book]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapter' : ActorMethod<[string], [] | [Chapter]>,
  'getChaptersForBook' : ActorMethod<[string], Array<Chapter>>,
  'getCharacterCount' : ActorMethod<[string], [] | [bigint]>,
  'getHighlightColors' : ActorMethod<[], Array<string>>,
  'getHighlights' : ActorMethod<[string], Array<Highlight>>,
  'getImageAttachment' : ActorMethod<[string], [] | [ImageAttachment]>,
  'getPolishVoices' : ActorMethod<[], Array<string>>,
  'getReadingSpeeds' : ActorMethod<[], Array<string>>,
  'getUserLanguagePreference' : ActorMethod<[], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoicePreference' : ActorMethod<[string], [] | [VoicePreference]>,
  'improveText' : ActorMethod<[string, string], string>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listImageAttachments' : ActorMethod<[], Array<ImageAttachment>>,
  'removeBoldRange' : ActorMethod<[string, bigint, bigint], undefined>,
  'removeHighlight' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSynonymsWithVoiceInput' : ActorMethod<[string], Array<string>>,
  'searchWithVoiceInput' : ActorMethod<[string, string], [] | [string]>,
  'setUserLanguagePreference' : ActorMethod<[string], undefined>,
  'setVoicePreference' : ActorMethod<[string, string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAnnotation' : ActorMethod<[string, string], undefined>,
  'updateBook' : ActorMethod<[string, string, string], undefined>,
  'updateChapter' : ActorMethod<[string, string, string, string], undefined>,
  'uploadImageAttachment' : ActorMethod<[string, string, Uint8Array], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];