/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExportResult = IDL.Record({
  'data' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const Book = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Annotation = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'chapterId' : IDL.Text,
});
export const BoldRange = IDL.Record({
  'end' : IDL.Nat,
  'chapterId' : IDL.Text,
  'start' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Chapter = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'characterCount' : IDL.Nat,
  'bookId' : IDL.Text,
});
export const Highlight = IDL.Record({
  'end' : IDL.Nat,
  'color' : IDL.Text,
  'text' : IDL.Text,
  'chapterId' : IDL.Text,
  'start' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageAttachment = IDL.Record({
  'id' : IDL.Text,
  'contentType' : IDL.Text,
  'data' : ExternalBlob,
  'size' : IDL.Nat,
  'filename' : IDL.Text,
});
export const VoicePreference = IDL.Record({
  'voice' : IDL.Text,
  'chapterId' : IDL.Text,
  'speed' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAnnotation' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addAttachmentToChapter' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addBoldRange' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'addHighlight' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'adjustBoldRanges' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'adjustHighlights' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'analyzePolishWriting' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkEnglishSpelling' : IDL.Func([IDL.Text], [IDL.Text], []),
  'checkPolishSpelling' : IDL.Func([IDL.Text], [IDL.Text], []),
  'clearBoldRanges' : IDL.Func([IDL.Text], [], []),
  'clearHighlights' : IDL.Func([IDL.Text], [], []),
  'createBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteAnnotation' : IDL.Func([IDL.Text], [], []),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'deleteChapter' : IDL.Func([IDL.Text], [], []),
  'deleteImageAttachment' : IDL.Func([IDL.Text], [], []),
  'exportChapterAsDocx' : IDL.Func([IDL.Text], [ExportResult], []),
  'exportChapterAsPdf' : IDL.Func([IDL.Text], [ExportResult], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAnnotationsForChapter' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Annotation)],
      ['query'],
    ),
  'getAttachmentsForChapter' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAvailableFonts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBoldRanges' : IDL.Func([IDL.Text], [IDL.Vec(BoldRange)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapter' : IDL.Func([IDL.Text], [IDL.Opt(Chapter)], ['query']),
  'getChaptersForBook' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
  'getCharacterCount' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getHighlightColors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getHighlights' : IDL.Func([IDL.Text], [IDL.Vec(Highlight)], ['query']),
  'getImageAttachment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ImageAttachment)],
      ['query'],
    ),
  'getPolishVoices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getReadingSpeeds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserLanguagePreference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoicePreference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VoicePreference)],
      ['query'],
    ),
  'improveText' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listImageAttachments' : IDL.Func([], [IDL.Vec(ImageAttachment)], ['query']),
  'removeBoldRange' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'removeHighlight' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSynonymsWithVoiceInput' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'searchWithVoiceInput' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'setUserLanguagePreference' : IDL.Func([IDL.Text], [], []),
  'setVoicePreference' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAnnotation' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'uploadImageAttachment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExportResult = IDL.Record({
    'data' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const Book = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Annotation = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'chapterId' : IDL.Text,
  });
  const BoldRange = IDL.Record({
    'end' : IDL.Nat,
    'chapterId' : IDL.Text,
    'start' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Chapter = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'characterCount' : IDL.Nat,
    'bookId' : IDL.Text,
  });
  const Highlight = IDL.Record({
    'end' : IDL.Nat,
    'color' : IDL.Text,
    'text' : IDL.Text,
    'chapterId' : IDL.Text,
    'start' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageAttachment = IDL.Record({
    'id' : IDL.Text,
    'contentType' : IDL.Text,
    'data' : ExternalBlob,
    'size' : IDL.Nat,
    'filename' : IDL.Text,
  });
  const VoicePreference = IDL.Record({
    'voice' : IDL.Text,
    'chapterId' : IDL.Text,
    'speed' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAnnotation' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addAttachmentToChapter' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addBoldRange' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'addHighlight' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'adjustBoldRanges' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'adjustHighlights' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'analyzePolishWriting' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkEnglishSpelling' : IDL.Func([IDL.Text], [IDL.Text], []),
    'checkPolishSpelling' : IDL.Func([IDL.Text], [IDL.Text], []),
    'clearBoldRanges' : IDL.Func([IDL.Text], [], []),
    'clearHighlights' : IDL.Func([IDL.Text], [], []),
    'createBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createChapter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteAnnotation' : IDL.Func([IDL.Text], [], []),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'deleteChapter' : IDL.Func([IDL.Text], [], []),
    'deleteImageAttachment' : IDL.Func([IDL.Text], [], []),
    'exportChapterAsDocx' : IDL.Func([IDL.Text], [ExportResult], []),
    'exportChapterAsPdf' : IDL.Func([IDL.Text], [ExportResult], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAnnotationsForChapter' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Annotation)],
        ['query'],
      ),
    'getAttachmentsForChapter' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAvailableFonts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBoldRanges' : IDL.Func([IDL.Text], [IDL.Vec(BoldRange)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapter' : IDL.Func([IDL.Text], [IDL.Opt(Chapter)], ['query']),
    'getChaptersForBook' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
    'getCharacterCount' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getHighlightColors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getHighlights' : IDL.Func([IDL.Text], [IDL.Vec(Highlight)], ['query']),
    'getImageAttachment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ImageAttachment)],
        ['query'],
      ),
    'getPolishVoices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getReadingSpeeds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserLanguagePreference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoicePreference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VoicePreference)],
        ['query'],
      ),
    'improveText' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listImageAttachments' : IDL.Func(
        [],
        [IDL.Vec(ImageAttachment)],
        ['query'],
      ),
    'removeBoldRange' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'removeHighlight' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSynonymsWithVoiceInput' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'searchWithVoiceInput' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'setUserLanguagePreference' : IDL.Func([IDL.Text], [], []),
    'setVoicePreference' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAnnotation' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateChapter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'uploadImageAttachment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };